cServer: server.cpp
	g++ -Wall -std=c++17 -o server.exe server.cpp -lws2_32
cClient: client.cpp
	g++ -Wall -std=c++17 -o client.exe client.cpp -lws2_32
all: server.cpp client.cpp
	g++ -Wall -std=c++17 -o server.exe server.cpp -lws2_32
	g++ -Wall -std=c++17 -o client.exe client.cpp -lws2_32